# perform checks on a file

# check the technical writing for various characteristics
- writing/reflection.md:
    - description: Ensure that reflection.md file exists in the writing/ directory
      check: ConfirmFileExists
    # - description: Write a minimum number of meaningful words in the reflection
    #   check: CountFileWords
    #   options:
    #     count: 400
    #     exact: false
    - description: Complete all TODOs, remove the TODO markers in the reflection.md
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true

- src/code.r:
    - description: Ensure that code.r file exists in the src/ directory
      check: ConfirmFileExists
    # - description: Write a minimum number of meaningful words in the code
    #   check: CountFileWords
    #   options:
    #     count: 400
    #     exact: false
    - description: Complete all TODOs, remove the TODO markers in the code.r
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true

# count number of commits in the GitHub repository
- description: Have at least a specific minimum number of commits (4) in repository
  check: CountCommits
  options:
    count: 4
